name: Run Gradle on PRs
on: [pull_request,push]
env:
  gradleVersion: 7.3.2
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          distribution: 'adopt'
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        name: Build
        with:
          gradle-version: ${{ env.gradleVersion }}
          arguments: build
      - name: List
        run: ls -la build/reports/jacoco/test/jacocoTestReport.xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
      - name: List
        run: ls -la build/reports/jacoco/test/jacocoTestReport.xml
